// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmxbdmbsomaebedlinai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteGJkbWJzb21hZWJlZGxpbmFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjQyMzIsImV4cCI6MjA2MjU0MDIzMn0.6lZ7TygKyxBesug1Poj7pkoopFnAetdl4FZeRuj1DsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);